### ISSUE TITLE
HTTP port is declared as terraform variable

### ISSUE THREAD

**Issue by ADobrodey** [deepan4cloud/terraform-aws-simple-httpserver#2]
https://github.com/deepan4cloud/terraform-aws-simple-httpserver/blob/b38bf525347b8a13abede3f5e49f74f4754677cd/main.tf#L82

The port is declared as variable but works only with default value(80), because it's hardcoded in webserver.py, I'd prefer to see this port as hardcoded (terraform locals) or passed into the webserver as environment variable from userdata or webserver.py generated as templatefile.
Same for var.ssh_port - it's used for SGs but you don't modify sshd_conf with new listen port for the SSH demon

**Comment by deepanrepo** [comment]
Agree with you @ADobrodey. It should be dynamic. As you suggested, I've used locals to pass the port # as well as webserver.py to get the port # while starting the webserver. 
For ssh_port, it is needed if someone wants to run ssh in different port than 22. Otherwise it doesn't need to be modified/added in sshd_conf. Don't want to complicate it. hence have removed it from tfvars.

We can use something similar to below script inside an instance to replace the port.
ex:-

#!/bin/bash -ex
 perl -pi -e 's/^#?Port 22$/Port 6666/' /etc/ssh/sshd_config
 service sshd restart || service ssh restart

Thanks for all your suggestions :)
